---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(dplyr)
library(echarts4r)
library(geojsonio)
library(sp)
library(ivs)
```


```{r mapas numero}


ymm<-sf::st_read("https://raw.githubusercontent.com/ibaitamayo/utilidades/main/Mapas/ZBSNavarra%20Geojson/idena.navarra.es_20220704_165004.json")

ymm %>% mutate(CZONA=as.character(CZONA))->ymm
as.data.frame(ymm)%>% dplyr::select(c("CZONA" ,"ZONA"))->Zona_Czona
navarra_small <-geojsonio::geojson_list(ymm)


pu142 %>% group_by(tipop,ZONA) %>% summarise(n=median(npers,na.rm=TRUE)) %>% 
  e_charts(ZONA) %>% 
  e_map_register("Navarra",navarra_small)  %>% 
  e_map(map = "Navarra",serie = n, nameProperty ="ZONA") %>% 
e_visual_map(n) %>% 
  e_title("Mediana de número de contratos por persona", left = "center") 
  




```


```{r movilidad entre ZBS}


point<-sf::st_read("https://raw.githubusercontent.com/ibaitamayo/utilidades/main/idena.navarra.es_20240111_150653.json")


seal_coords <- do.call(rbind, sf::st_geometry(point)) %>% 
as_tibble() %>% cbind(point$ZONA)%>% setNames(c("lon","lat","ZONA")) 



pu142 %>% distinct(zbsa,ZONA) ->referzon
referzon %>% left_join(seal_coords,by="ZONA")->zongeom
colnames(referzon)<-c("zbs2","ZONA_2")


pu142 %>% left_join(referzon, by="zbs2") %>% 
  e_charts(ZONA) |> 
  e_map_register("Navarra",navarra_small)  %>% 
  e_map(map = "Navarra",serie = n, nameProperty ="ZONA") %>%
  e_lines(
    source_name=ZONA,
  target_name=ZONA_2,
    name = "flights",
    lineStyle = list(normal = list(curveness = 0.3))
   )

```

```{r y como procesos}

tr142%>% dplyr::select("no_pers","iniciocontrato","zbs","tipop" )->eventlog_Charls_multiple
colnames(eventlog_Charls_multiple)[1]<-"ID"
eventlog_Charls_multiple %>% group_by(ID,zbs) %>% arrange(iniciocontrato) %>% mutate(num_contr=1:n()) %>% ungroup()->eventlog_Charls_multiple_

Evnt.log.Char_ =eventlog_Charls_multiple_ %>% 
  mutate(activity_instance = 1:nrow(.),
         resource = tipop,
         status = "complete") %>% 
  eventlog(
    case_id = "ID", #ID del paciente
    activity_id = "zbs", #Nombre de la actividad
    lifecycle_id = "status", #Nombre del estado de la actividad
    activity_instance_id = "activity_instance", #ID de la actividad que referencia el evento
    timestamp = "iniciocontrato", #Fecha del evento
    resource_id = "resource" #Resource
  )

summary(Evnt.log.Char_) 
Evnt.log.Char_ %>%
  trace_explorer(n_traces = 10)
Evnt.log.Char_ %>%
  filter_activity_frequency(percentage = 1) %>% # show only most frequent activities
  filter_trace_frequency(percentage = 0.15) %>%
  process_map( #Visión temporal de los nodos, cuánto tiempo de media o mediana o lo que selecciones se tarda en realizar una actividad, en nuestro caso es 0 porque las actividades solo tienen un evento, no hay un inicio y un final
              type_edges = performance(median, "months")) #Visión temporal de las aristas, el tiempo que hay entre el final de una actividad y el inicio de la siguiente (puede ser tiempo negativo si la siguiente empieza antes de que acabe la primera)

```

